### ISSUE TITLE
invalid iteral

### ISSUE THREAD

**Issue by AG-597** [tn3w/flask_Captchaify#15]
`Invalid literal for int() with base 10: '123, 16'`

How can i fix this?

**Comment by tn3w** [comment]
Hello @AG-597, can you please tell me where the error occurred or provide an error stack trace?
You can find a detailed error description in the log.txt file. Use the command `pip show flask_Captchaify`, e.g.: “Location: C:\Users\<USER>\anaconda3\Lib\site-packages”, and copy this value.

The file is located under <COPIED_DIR>\flask_Captchaify\log.txt

If more than one error is stored in the file, you can search for the correct error stack trace by searching for the error ID that is in the console with the error, e.g. [flask_Captchaify Error #<ERRORID> at 2024-07-20 21:49:09]

An error stacktrace in the file looks like this:
```txt
----- Error #ERRORID at 2024-07-20 21:49:09 -----
Traceback (most recent call last):
  File "C:\Users\user\Documents\Code\flask_Captchaify\src\flask_Captchaify\__init__.py", line 2065, in _set_cookies
    print(g.captchaify_no_new_cookies)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Documents\Code\flask_Captchaify\.venv\Lib\site-packages\flask\ctx.py", line 56, in __getattr__
    raise AttributeError(name) from None
AttributeError: captchaify_no_new_cookies
```

Thank you for reporting the error.

**Comment by AG-597** [comment]
Hello! I did not get a stack trace, but no connections went through, everytime I tried connecting, it printed `[flask_Captchaify Error #ERROR_ID at 2024-07-20 21:49:09]: Invalid literal for int() with base 10: '123, 16'` is there a way to find the stack trace based off this message?

**Comment by tn3w** [comment]
In the latest version 1.8.4, which can be installed with `pip install flask_Captchaify==1.8.4`, I have added the debug parameter which does not log the errors, but raises them directly.

Here is an example on how to enable debug mode:
```python
captchaify = Captchaify(app, debug = True)
```

If debug is activated correctly, the message “[flask_Captchaify] Debug mode is activated.” should appear.
Now you should actually see an error stacktrace.

Thank you for your patience, if you find the error stacktrace, please send it so I can fix it in a timely manner to improve everyone's user and admin experience.

**Comment by tn3w** [comment]
If for some reason you cannot update to this version, you can also try the following step:
(Important: If this fixes the error for you, it can still happen that it occurs again, or that the same thing happens to other users. Therefore, a specific error message would still be important).
- Delete all flask_Captchaify files and install again: The error could be due to a corrupt file, first find out where the package is located and delete all files, then reinstall it with the command `pip install flask_Captchaify --upgrade`.
- The error could be due to a third party, set the third_parties parameter to `[]` as here:
   ```python
   captchaify = Captchaify(app, third_parties = [])
   ```
- Do not use the local address to call flask_Captchaify or set `ipify` in the third_parties setting to automatically get the correct ip like here:
   ```python
   captchaify = Captchaify(app, third_parties = ['geoip', 'tor', 'ipapi', 'stopforumspam', 'ipify'])
   ```

If the error still occurs, you can try to localize log.txt again.

**Comment by tn3w** [comment]
Since I have not received a reply, I assume that the error has been corrected and I am therefore closing this issue. If there are any questions or further problems that belong to the same topic, the issue can be reopened; if there is a problem of a different kind, a new Issue can be created.

Thank you for your support in improving this project.

Further reading: [README](https://github.com/tn3w/flask_Captchaify/blob/master/README.md), [Contributing Guidelines](https://github.com/tn3w/flask_Captchaify/blob/master/README.md), [Security Policy](https://github.com/tn3w/flask_Captchaify/blob/master/SECURITY.md) and [Code of Conduct](https://github.com/tn3w/flask_Captchaify/blob/master/CODE_OF_CONDUCT.md).
