### ISSUE TITLE
Disable the use of external websites like `stopforumspam`.

### ISSUE THREAD

**Issue by AAA3A-AAA3A** [tn3w/flask_Captchaify#3]
Hello,

I'd like to use this Flask extension to protect my web project, but the host I use prevents web requests to external websites. Would it be possible to add a parameter to disable this, or to ignore an HTTP error?
```
requests.exceptions.ProxyError: HTTPSConnectionPool(host='[api.stopforumspam.org](http://api.stopforumspam.org/)', port=443): Max retries exceeded with url: /api?ip=...&json (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 403 Forbidden')))
```

Thank you in advance,
Have a nice day.

**Comment by tn3w** [comment]
Thank you for disclosing this issue

With version 1.6.1 you can now activate certain third parties, it has also been fixed that an error message appears with the incorrect request from third parties.

Even if the issue has been fixed, it is better to disable the stopforumspam api, because then less time is needed

Here is an example of deactivating all third parties:
```python
captcha = Captcha(app, third_parties = [])
```

Here is an example of deactivating only stopforumspam:
```python
captcha = Captcha(app, third_parties = ["tor", "ipapi"])
```

To see all the changes click here: https://github.com/tn3w/flask_DDoSify/compare/v1.6...2cd41680ef11b9cf63aa7578873755e70e70ad0f

**Comment by AAA3A-AAA3A** [comment]
Thank you for your help!
